### ISSUE TITLE
Exception in InitSession method

### ISSUE THREAD

**Issue by dadim** [imperyal/synopse-login#1]
I've noticed (at least in Firefox) the following exception, when attempting to call APP_Login.CloseSession():

Uncaught TypeError: self.getPrefixed is not a function

I modified slightly the source to handle this exception and, by the way, I renamed the other instances of the _self_ variable to a block variable _me_ to avoid coincidences with the built in self. I've attached the modified file.

[synLoginClass.zip](https://github.com/imperyal/synopse-login/files/5965379/synLoginClass.zip)

**Comment by imperyal** [comment]
The bug is now fixed, I kept the `self = this` is the code because I believe most people will be familiarized with that.

Thank you @dadim
